/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonTextAlignJustify: typeof import('~icons/carbon/text-align-justify')['default']
    IEpFolder: typeof import('~icons/ep/folder')['default']
    IEpMonitor: typeof import('~icons/ep/monitor')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
