// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ICarbonTextAlignJustify: typeof import('~icons/carbon/text-align-justify')['default']
    IEpFolder: typeof import('~icons/ep/folder')['default']
    IEpMonitor: typeof import('~icons/ep/monitor')['default']
    IIconsElementPlus: typeof import('~icons/icons/element-plus')['default']
    IIconsNuxt: typeof import('~icons/icons/nuxt')['default']
    IIconsPinia: typeof import('~icons/icons/pinia')['default']
    IIconsUnocss: typeof import('~icons/icons/unocss')['default']
    IIconsVite: typeof import('~icons/icons/vite')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
